#!/bin/bash

# %Id%
debug_off=${1:-"ON"}
build_path="/tmp/mon/build"
install_path="/tmp/mon/package"
current_path=$PWD
build_threads=$(($(cat /proc/cpuinfo| grep family | wc -l)+1))
function run_cmd
{
  name=$1
  cmd=$2
  echo "--> $name ($cmd)"
  $cmd
  if (($?>0))
  then
    exit 1
  fi
}

function build()
{
  path=$1
  echo "-------------------> Building $path <-------------------"
  object_build_path="$build_path/$path"
  object_path="$current_path/$path"
  mkdir -p $object_build_path
  cd $object_build_path
  run_cmd "CMake" "cmake -DCMAKE_INSTALL_PREFIX='$install_path' -DBUILD_SERVER=ON -DBUILD_DEBUG=$debug_off $object_path"
  run_cmd "make" "make -j$build_threads"
  run_cmd "install" "make install"
  cd $build_path
}

mkdir -p $build_path
mkdir -p $install_path
build "application"
build "sensors/cpu"
build "sensors/memory"
cd $current_path
