#!/bin/bash

. ./linux-environment

mkdir -p ${root_path}
mkdir -p ${build_path}
mkdir -p ${install_path}
mkdir -p ${conf_path}
mkdir -p ${log_path}
mkdir -p ${data_path}
mkdir -p ${run_path}

cp doc/config/node.conf ${conf_path}
cp doc/config/node.cpu.conf ${conf_path}
cp doc/config/node.memory.conf ${conf_path}
cp doc/config/node.logger.conf ${conf_path}
cp doc/config/collector.conf ${conf_path}
cp doc/config/collector.node.localhost.conf ${conf_path}

mkdir -p "${ide_build_path}/application"
for s in $(ls -1 sensors)
do 
    mkdir -p "${ide_build_path}/sensors/${s}"
done

ln -s ${root_path} ../work
