#!/bin/bash

# %Id%

. ./linux-environment

debug_off=${1:-"ON"}
use_clang=${2:-"OFF"}
verbose_build=${3:-"OFF"}
current_path=$PWD
function run_cmd
{
  name=$1
  cmd=$2
  echo "--> $name ($cmd)"
  echo $cmd >> ${console_build_path}/commands
  $cmd
  if (($?>0))
  then
    exit 1
  fi
}

function build()
{
  path=$1
  object_build_path="$console_build_path/$path"
  echo "------------------- Building ${path} in ${object_build_path} -------------------"
  rm -rf ${object_build_path}
  object_path="$current_path/$path"
  mkdir -p $object_build_path
  cd $object_build_path
  run_cmd "CMake" "cmake -DCMAKE_INSTALL_PREFIX='$install_path' -DMON_VERBOSE_BUILD=$verbose_build -DBUILD_DEBUG=$debug_off -DMON_USE_CLANG=$use_clang  $object_path"
  run_cmd "make" "make -j$build_threads"
  run_cmd "install" "make install"
  cd $build_path
}

mkdir -p $console_build_path
mkdir -p $install_path
build "application"
build "sensors/cpu"
build "sensors/memory"
cd $current_path
