#!/bin/bash

. ./linux-environment

#filelist=( application/libraryes/config/src/rw/cconfigurationparcer.cpp )
filelist=( application/daemons/collector/main.cpp )
include="-I application/libraryes/base/src
	 -I application/libraryes/base/src/parcer
	 -I application/libraryes/base/src/singleton
         -I application/libraryes/network/src
         -I application/libraryes/logger/src
         -I application/libraryes/config/src
         -I application/libraryes/config/src/rw
         -I application/libraryes/config/src/model
         -I application/libraryes/sensor/src
         -I application/libraryes/sensor/src/data
         -I application/libraryes/sensor/src/parcers
         -I application/libraryes/protocol/src
         -I application/defines 
         -I application 
         -I /tmp/mon/build/console/application/mon_generated_sources"
          
#echo ${include}

for f in $filelist
do
  g++ -DMON_DEBUG -E $f $include
done
