# %Id%
include (${CMAKE_INSTALL_PREFIX}/include/mon/CMakeDebug.cmake)
set( GEN_PATH "${PROJECT_BINARY_DIR}/mon_generated_sources" )
set( SENSOR_DEFINITION "${GEN_PATH}/definition.h" )
file(MAKE_DIRECTORY ${GEN_PATH})
file(WRITE  ${GEN_PATH}/generated.h "/* Generated by CMake */\n\n#ifndef MON_CMAKE_GENERATED\n#define MON_CMAKE_GENERATED\n\n"  )
file(APPEND ${GEN_PATH}/generated.h "#include \"${SENSOR_DEFINITION}\"\n"  )
file(APPEND ${GEN_PATH}/generated.h "\n#endif\n" )

function(add_sensor sources headers include_paths)
  MESSAGE ( STATUS "---------- Processing `${EXECUTABLE_NAME}` sensor ----------" )
  add_custom_command(
    OUTPUT    ${GEN_PATH}/definition.h
    COMMAND   ${CMAKE_INSTALL_PREFIX}/bin/mon-text-to-char-array
    ARGS      ${CMAKE_SOURCE_DIR}/src/definition.txt ${SENSOR_DEFINITION} definition
    DEPENDS   ${CMAKE_SOURCE_DIR}/src/definition.txt
    COMMENT   "Convert text to C char array"
  )
  include_directories( ${CMAKE_INSTALL_PREFIX}/include/mon ${GEN_PATH} ${include_paths})
  add_library( ${EXECUTABLE_NAME} SHARED ${sources} ${headers} ${SENSOR_DEFINITION})
  target_link_libraries( ${EXECUTABLE_NAME} )
  INSTALL( TARGETS ${EXECUTABLE_NAME} LIBRARY DESTINATION lib/mon/sensors )
endfunction()
