OPTION ( BUILD_DEBUG "Build the project using debugging code" OFF )
OPTION ( MON_VERBOSE_BUILD "Verbose build project" OFF )
if(MON_VERBOSE_BUILD)
  SET( CMAKE_VERBOSE_MAKEFILE ON )
endif(MON_VERBOSE_BUILD)

IF( BUILD_DEBUG )
    MESSAGE ( STATUS "---> Build with debug info" )
    SET( CMAKE_BUILD_TYPE Debug )
    ADD_DEFINITIONS( -DMON_DEBUG )
    ADD_DEFINITIONS( -g )
    IF(MON_USE_GCC)
      #ADD_DEFINITIONS( -ftest-coverage )
      ADD_DEFINITIONS( -fprofile-arcs )
      SET(GLOBAL_LINK_LIBS gcov )
    ENDIF(MON_USE_GCC)
ELSE( BUILD_DEBUG )
    IF(UNIX)
        ADD_DEFINITIONS( -O2 )
    ENDIF(UNIX)
ENDIF( BUILD_DEBUG )

IF(UNIX)
    ADD_DEFINITIONS( -Wall )
ENDIF(UNIX)
