#ifndef PROTOCOLCONTROLCHARACTERS_H
#define PROTOCOLCONTROLCHARACTERS_H

#define MON_PROTO_TYPE_DELIMITER '!'
#define MON_PROTO_ENDL           '\n'
#define MON_DATA_SENSORNAME_I_FRAMENAME_DELIMITER      ":"
#define MON_DATA_SENSOR_HEADER_I_FRAMESETS_DELIMITER   "!"
#define MON_DATA_SENSOR_FRAMENUMBER_I_FIELDS_DELIMITER "#"
#define MON_DATA_SENSOR_FRAME_I_FRAME_DELIMITER        "|"
#define MON_DATA_SENSOR_FIELD_I_FIELD_DELIMITER        ":"


#define MON_PROTO_ID_COLLECTOR_TO_NODE_CONNECT  1
#define MON_PROTO_ID_CONNECT_ANSWER             2
#define MON_PROTO_ID_REQUEST_NODE_SENSORS_LIST  3
#define MON_PROTO_ID_ANSWER_NODE_SENSORS_LIST   4
#define MON_PROTO_ID_REQUEST_SENSOR_DEFINITION  5
#define MON_PROTO_ID_ANSWER_SENSOR_DEFINITION   6

#endif // PROTOCOLCONTROLCHARACTERS_H
